
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - events/status
  verbs:
  - get
  - list
- apiGroups:
  - events.quad.com
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.quad.com
  resources:
  - notifications/status
  verbs:
  - get
  - patch
  - update
